name: Deploy

on:
  workflow_dispatch:
    inputs:
      cf_space:
        description: 'Specify the Cloud Foundry space to deploy to'
        required: true
      repository_id:
        description: 'Specify the Repository ID (leave blank if deploying to developcap)'
        required: false

permissions:
  pull-requests: read
  packages: read

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop_deploy

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - run: cat /home/runner/.m2/settings.xml
      - name: Set REPOSITORY_ID
        id: set_repository_id
        run: |
          if [ "${{ github.event.inputs.cf_space }}" = "developcap" ]; then
            echo "Using REPOSITORY_ID from secrets"
            echo "::set-output name=repository_id::${{ secrets.REPOSITORY_ID }}"
          else
            if [ -z "${{ github.event.inputs.repository_id }}" ]; then
              echo "REPOSITORY_ID must be provided for non-developcap spaces"
              exit 1
            else
              echo "Using provided REPOSITORY_ID"
              echo "::set-output name=repository_id::${{ github.event.inputs.repository_id }}"
            fi
          fi

      - name: Build with Maven
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: | 
          cd cap-notebook/demoapp
          
          # Replace placeholder with actual REPOSITORY_ID value
          sed -i 's|__REPOSITORY_ID__|'${{ steps.set_repository_id.outputs.repository_id }}'|g' ./mta.yaml
          
          mvn --batch-mode clean install
